{application,tcp_server,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{tcp_server_app,[]}},
              {env,[]},
              {modules,[tcp_server,tcp_server_SUITE,tcp_server_app,
                        tcp_server_sup,tcp_server_tests]}]}.
